# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='records')),
                ('text', models.TextField()),
                ('dc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
