# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wav',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='generated_wav/%d-%m-%Y/', verbose_name='Файл')),
                ('text', models.TextField(verbose_name='Фраза')),
                ('config', models.CharField(blank=True, max_length=255)),
                ('command', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Созданные wav',
                'verbose_name': 'Созданный wav',
            },
        ),
    ]
