# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wav',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='generated_wav', verbose_name='Файл')),
                ('text', models.TextField(verbose_name='Фраза')),
                ('config', models.CharField(blank=True, max_length=255)),
                ('command', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Созданный wav',
                'verbose_name_plural': 'Созданные wav',
            },
        ),
    ]
