# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundfile',
            name='dc',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 26, 14, 5, 59, 993967, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soundfile',
            name='type',
            field=models.CharField(choices=[('wav', 'wav')], default='wav', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='file',
            field=models.FileField(upload_to='/opt/voice-synthesizer/generated'),
        ),
    ]
