# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wav',
            name='file',
            field=models.FileField(upload_to='generated_wav/%d-%m-%Y/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='wav',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
